// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_helmfile

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func HelmfileProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"additional_plugins": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "List of additional helm plugins to install.",
				MarkdownDescription: "List of additional helm plugins to install.",
			},
			"default_args": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "List of default arguments to pass to every helmfile command.",
				MarkdownDescription: "List of default arguments to pass to every helmfile command.",
			},
			"disable_force_update": schema.BoolAttribute{
				Optional:            true,
				Description:         "do not force helm repos to update when executing \"helm repo add\"",
				MarkdownDescription: "do not force helm repos to update when executing \"helm repo add\"",
			},
			"enforce_plugin_verification": schema.BoolAttribute{
				Optional:            true,
				Description:         "enforce helm plugin verification when installing missing plugins",
				MarkdownDescription: "enforce helm plugin verification when installing missing plugins",
			},
			"helm_binary_path": schema.StringAttribute{
				Optional:            true,
				Description:         "Path to the helm binary. If not set, the provider will look for 'helm' in the system PATH.",
				MarkdownDescription: "Path to the helm binary. If not set, the provider will look for 'helm' in the system PATH.",
			},
			"helm_oci_plain_http": schema.BoolAttribute{
				Optional:            true,
				Description:         "allow using plain HTTP when pulling charts from OCI registries",
				MarkdownDescription: "allow using plain HTTP when pulling charts from OCI registries",
			},
			"kustomize_binary_path": schema.StringAttribute{
				Optional:            true,
				Description:         "Path to the kustomize binary. If not set, the provider will look for 'kustomize' in the system PATH.",
				MarkdownDescription: "Path to the kustomize binary. If not set, the provider will look for 'kustomize' in the system PATH.",
			},
			"perform_init": schema.BoolAttribute{
				Optional:            true,
				Description:         "Whether to run 'helmfile init' before applying any helmfile operations.",
				MarkdownDescription: "Whether to run 'helmfile init' before applying any helmfile operations.",
			},
			"skip_deps": schema.BoolAttribute{
				Optional:            true,
				Description:         "skip running \"helm repo update\" and \"helm dependency build\"",
				MarkdownDescription: "skip running \"helm repo update\" and \"helm dependency build\"",
			},
			"skip_refresh": schema.BoolAttribute{
				Optional:            true,
				Description:         "skip running 'helmfile repos' before applying any helmfile operations.",
				MarkdownDescription: "skip running 'helmfile repos' before applying any helmfile operations.",
			},
			"strip_args_values_on_exit_error": schema.BoolAttribute{
				Optional:            true,
				Description:         "Strip the potential secret values of the helm command args contained in a helmfile error message (default true)",
				MarkdownDescription: "Strip the potential secret values of the helm command args contained in a helmfile error message (default true)",
			},
		},
	}
}

type HelmfileModel struct {
	AdditionalPlugins          types.List   `tfsdk:"additional_plugins"`
	DefaultArgs                types.List   `tfsdk:"default_args"`
	DisableForceUpdate         types.Bool   `tfsdk:"disable_force_update"`
	EnforcePluginVerification  types.Bool   `tfsdk:"enforce_plugin_verification"`
	HelmBinaryPath             types.String `tfsdk:"helm_binary_path"`
	HelmOciPlainHttp           types.Bool   `tfsdk:"helm_oci_plain_http"`
	KustomizeBinaryPath        types.String `tfsdk:"kustomize_binary_path"`
	PerformInit                types.Bool   `tfsdk:"perform_init"`
	SkipDeps                   types.Bool   `tfsdk:"skip_deps"`
	SkipRefresh                types.Bool   `tfsdk:"skip_refresh"`
	StripArgsValuesOnExitError types.Bool   `tfsdk:"strip_args_values_on_exit_error"`
}
