// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_helmfile_release

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kaweezle/terraform-provider-helmfile/internal/provider/utils"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func HelmfileReleaseResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_no_matching_release": schema.BoolAttribute{
				Optional:            true,
				Description:         "Do not exit with an error code if the provided selector has no matching releases.",
				MarkdownDescription: "Do not exit with an error code if the provided selector has no matching releases.",
			},
			"args": schema.StringAttribute{
				Optional:            true,
				Description:         "Pass args to helm exec.",
				MarkdownDescription: "Pass args to helm exec.",
			},
			"cascade": schema.StringAttribute{
				Optional:            true,
				Description:         "Pass cascade to helm exec, default: background.",
				MarkdownDescription: "Pass cascade to helm exec, default: background.",
			},
			"chart": schema.StringAttribute{
				Optional:            true,
				Description:         "Set chart. Uses the chart set in release by default.",
				MarkdownDescription: "Set chart. Uses the chart set in release by default.",
			},
			"concurrency": schema.Int64Attribute{
				Optional:            true,
				Description:         "Maximum number of concurrent helm processes to run, 0 is unlimited.",
				MarkdownDescription: "Maximum number of concurrent helm processes to run, 0 is unlimited.",
			},
			"context": schema.Int64Attribute{
				Optional:            true,
				Description:         "Output NUM lines of context around changes.",
				MarkdownDescription: "Output NUM lines of context around changes.",
			},
			"debug": schema.BoolAttribute{
				Optional:            true,
				Description:         "Enable verbose output for Helm and set log-level to debug.",
				MarkdownDescription: "Enable verbose output for Helm and set log-level to debug.",
			},
			"detailed_exitcode": schema.BoolAttribute{
				Optional:            true,
				Description:         "Return a non-zero exit code 2 instead of 0 when there were changes detected AND the changes are synced successfully.",
				MarkdownDescription: "Return a non-zero exit code 2 instead of 0 when there were changes detected AND the changes are synced successfully.",
			},
			"diff_args": schema.StringAttribute{
				Optional:            true,
				Description:         "Pass args to helm helm-diff.",
				MarkdownDescription: "Pass args to helm helm-diff.",
			},
			"environment": schema.StringAttribute{
				Optional:            true,
				Description:         "Specify the environment name. Defaults to 'default'.",
				MarkdownDescription: "Specify the environment name. Defaults to 'default'.",
			},
			"file_or_path": schema.StringAttribute{
				Required:            true,
				Description:         "The path to the helmfile.yaml file or directory containing helmfile.yaml files.",
				MarkdownDescription: "The path to the helmfile.yaml file or directory containing helmfile.yaml files.",
			},
			"hide_notes": schema.BoolAttribute{
				Optional:            true,
				Description:         "Add --hide-notes flag to helm.",
				MarkdownDescription: "Add --hide-notes flag to helm.",
			},
			"include_needs": schema.BoolAttribute{
				Optional:            true,
				Description:         "Automatically include releases from the target release's 'needs' when --selector/-l flag is provided.",
				MarkdownDescription: "Automatically include releases from the target release's 'needs' when --selector/-l flag is provided.",
			},
			"include_tests": schema.BoolAttribute{
				Optional:            true,
				Description:         "Enable the diffing of the helm test hooks.",
				MarkdownDescription: "Enable the diffing of the helm test hooks.",
			},
			"include_transitive_needs": schema.BoolAttribute{
				Optional:            true,
				Description:         "Like --include-needs, but also includes transitive needs (needs of needs).",
				MarkdownDescription: "Like --include-needs, but also includes transitive needs (needs of needs).",
			},
			"kube_context": schema.StringAttribute{
				Optional:            true,
				Description:         "Set kubectl context. Uses current context by default.",
				MarkdownDescription: "Set kubectl context. Uses current context by default.",
			},
			"kubeconfig": schema.StringAttribute{
				Optional:            true,
				Description:         "Use a particular kubeconfig file.",
				MarkdownDescription: "Use a particular kubeconfig file.",
				Validators: []validator.String{
					&utils.ExistingFileOrDirectoryValidator{AllowDirectory: false},
				},
			},
			"log_level": schema.StringAttribute{
				Optional:            true,
				Description:         "Set log level, default info.",
				MarkdownDescription: "Set log level, default info.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Helm release.",
				MarkdownDescription: "The name of the Helm release.",
			},
			"namespace": schema.StringAttribute{
				Optional:            true,
				Description:         "Set namespace. Uses the namespace set in the context by default.",
				MarkdownDescription: "Set namespace. Uses the namespace set in the context by default.",
			},
			"no_hooks": schema.BoolAttribute{
				Optional:            true,
				Description:         "Do not diff changes made by hooks.",
				MarkdownDescription: "Do not diff changes made by hooks.",
			},
			"output": schema.StringAttribute{
				Optional:            true,
				Description:         "Output format for diff plugin.",
				MarkdownDescription: "Output format for diff plugin.",
			},
			"post_renderer": schema.StringAttribute{
				Optional:            true,
				Description:         "Pass --post-renderer to 'helm template' or 'helm upgrade --install'.",
				MarkdownDescription: "Pass --post-renderer to 'helm template' or 'helm upgrade --install'.",
			},
			"post_renderer_args": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Pass --post-renderer-args to 'helm template' or 'helm upgrade --install'.",
				MarkdownDescription: "Pass --post-renderer-args to 'helm template' or 'helm upgrade --install'.",
			},
			"reset_values": schema.BoolAttribute{
				Optional:            true,
				Description:         "Override helmDefaults.reuseValues 'helm upgrade --install --reset-values'.",
				MarkdownDescription: "Override helmDefaults.reuseValues 'helm upgrade --install --reset-values'.",
			},
			"reuse_values": schema.BoolAttribute{
				Optional:            true,
				Description:         "Override helmDefaults.reuseValues 'helm upgrade --install --reuse-values'.",
				MarkdownDescription: "Override helmDefaults.reuseValues 'helm upgrade --install --reuse-values'.",
			},
			"selector": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar.",
				MarkdownDescription: "Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar.",
			},
			"set": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Additional values to be merged into the helm command --set flag.",
				MarkdownDescription: "Additional values to be merged into the helm command --set flag.",
			},
			"show_secrets": schema.BoolAttribute{
				Optional:            true,
				Description:         "Do not redact secret values in the diff output. Should be used for debug purpose only.",
				MarkdownDescription: "Do not redact secret values in the diff output. Should be used for debug purpose only.",
			},
			"skip_cleanup": schema.BoolAttribute{
				Optional:            true,
				Description:         "Stop cleaning up temporary values generated by helmfile and helm-secrets. Useful for debugging.",
				MarkdownDescription: "Stop cleaning up temporary values generated by helmfile and helm-secrets. Useful for debugging.",
			},
			"skip_crds": schema.BoolAttribute{
				Optional:            true,
				Description:         "If set, no CRDs will be installed on sync. By default, CRDs are installed if not already present.",
				MarkdownDescription: "If set, no CRDs will be installed on sync. By default, CRDs are installed if not already present.",
			},
			"skip_diff_on_install": schema.BoolAttribute{
				Optional:            true,
				Description:         "Skips running helm-diff on releases being newly installed on this apply.",
				MarkdownDescription: "Skips running helm-diff on releases being newly installed on this apply.",
			},
			"skip_needs": schema.BoolAttribute{
				Optional:            true,
				Description:         "Do not automatically include releases from the target release's 'needs' when --selector/-l flag is provided.",
				MarkdownDescription: "Do not automatically include releases from the target release's 'needs' when --selector/-l flag is provided.",
			},
			"skip_schema_validation": schema.BoolAttribute{
				Optional:            true,
				Description:         "Pass --skip-schema-validation to 'helm template' or 'helm upgrade --install'.",
				MarkdownDescription: "Pass --skip-schema-validation to 'helm template' or 'helm upgrade --install'.",
			},
			"state_values_file": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Specify state values in a YAML file. Used to override .Values within the helmfile template.",
				MarkdownDescription: "Specify state values in a YAML file. Used to override .Values within the helmfile template.",
			},
			"state_values_set": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Set state values on the command line. Used to override .Values within the helmfile template.",
				MarkdownDescription: "Set state values on the command line. Used to override .Values within the helmfile template.",
			},
			"state_values_set_string": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Set state STRING values on the command line. Used to override .Values within the helmfile template.",
				MarkdownDescription: "Set state STRING values on the command line. Used to override .Values within the helmfile template.",
			},
			"strip_trailing_cr": schema.BoolAttribute{
				Optional:            true,
				Description:         "Strip trailing carriage return on input.",
				MarkdownDescription: "Strip trailing carriage return on input.",
			},
			"suppress": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Suppress specified Kubernetes objects in the diff output. Can be provided multiple times.",
				MarkdownDescription: "Suppress specified Kubernetes objects in the diff output. Can be provided multiple times.",
			},
			"suppress_diff": schema.BoolAttribute{
				Optional:            true,
				Description:         "Suppress diff in the output. Usable in new installs.",
				MarkdownDescription: "Suppress diff in the output. Usable in new installs.",
			},
			"suppress_output_line_regex": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "A list of regex patterns to suppress output lines from the diff output.",
				MarkdownDescription: "A list of regex patterns to suppress output lines from the diff output.",
			},
			"suppress_secrets": schema.BoolAttribute{
				Optional:            true,
				Description:         "Suppress secrets in the diff output. Highly recommended to specify on CI/CD use-cases.",
				MarkdownDescription: "Suppress secrets in the diff output. Highly recommended to specify on CI/CD use-cases.",
			},
			"sync_args": schema.StringAttribute{
				Optional:            true,
				Description:         "Pass args to helm upgrade.",
				MarkdownDescription: "Pass args to helm upgrade.",
			},
			"sync_release_labels": schema.BoolAttribute{
				Optional:            true,
				Description:         "Sync release labels to the target release.",
				MarkdownDescription: "Sync release labels to the target release.",
			},
			"take_ownership": schema.BoolAttribute{
				Optional:            true,
				Description:         "Add --take-ownership flag to helm.",
				MarkdownDescription: "Add --take-ownership flag to helm.",
			},
			"validate": schema.BoolAttribute{
				Optional:            true,
				Description:         "Validate your manifests against the Kubernetes cluster you are currently pointing at.",
				MarkdownDescription: "Validate your manifests against the Kubernetes cluster you are currently pointing at.",
			},
			"values": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Additional value files to be merged into the helm command --values flag.",
				MarkdownDescription: "Additional value files to be merged into the helm command --values flag.",
			},
			"wait": schema.BoolAttribute{
				Optional:            true,
				Description:         "Override helmDefaults.wait setting 'helm upgrade --install --wait'.",
				MarkdownDescription: "Override helmDefaults.wait setting 'helm upgrade --install --wait'.",
			},
			"wait_for_jobs": schema.BoolAttribute{
				Optional:            true,
				Description:         "Override helmDefaults.waitForJobs setting 'helm upgrade --install --wait-for-jobs'.",
				MarkdownDescription: "Override helmDefaults.waitForJobs setting 'helm upgrade --install --wait-for-jobs'.",
			},
		},
	}
}

type HelmfileReleaseModel struct {
	AllowNoMatchingRelease  types.Bool   `tfsdk:"allow_no_matching_release"`
	Args                    types.String `tfsdk:"args"`
	Cascade                 types.String `tfsdk:"cascade"`
	Chart                   types.String `tfsdk:"chart"`
	Concurrency             types.Int64  `tfsdk:"concurrency"`
	Context                 types.Int64  `tfsdk:"context"`
	Debug                   types.Bool   `tfsdk:"debug"`
	DetailedExitcode        types.Bool   `tfsdk:"detailed_exitcode"`
	DiffArgs                types.String `tfsdk:"diff_args"`
	Environment             types.String `tfsdk:"environment"`
	FileOrPath              types.String `tfsdk:"file_or_path"`
	HideNotes               types.Bool   `tfsdk:"hide_notes"`
	IncludeNeeds            types.Bool   `tfsdk:"include_needs"`
	IncludeTests            types.Bool   `tfsdk:"include_tests"`
	IncludeTransitiveNeeds  types.Bool   `tfsdk:"include_transitive_needs"`
	KubeContext             types.String `tfsdk:"kube_context"`
	Kubeconfig              types.String `tfsdk:"kubeconfig"`
	LogLevel                types.String `tfsdk:"log_level"`
	Name                    types.String `tfsdk:"name"`
	Namespace               types.String `tfsdk:"namespace"`
	NoHooks                 types.Bool   `tfsdk:"no_hooks"`
	Output                  types.String `tfsdk:"output"`
	PostRenderer            types.String `tfsdk:"post_renderer"`
	PostRendererArgs        types.List   `tfsdk:"post_renderer_args"`
	ResetValues             types.Bool   `tfsdk:"reset_values"`
	ReuseValues             types.Bool   `tfsdk:"reuse_values"`
	Selector                types.List   `tfsdk:"selector"`
	Set                     types.List   `tfsdk:"set"`
	ShowSecrets             types.Bool   `tfsdk:"show_secrets"`
	SkipCleanup             types.Bool   `tfsdk:"skip_cleanup"`
	SkipCrds                types.Bool   `tfsdk:"skip_crds"`
	SkipDiffOnInstall       types.Bool   `tfsdk:"skip_diff_on_install"`
	SkipNeeds               types.Bool   `tfsdk:"skip_needs"`
	SkipSchemaValidation    types.Bool   `tfsdk:"skip_schema_validation"`
	StateValuesFile         types.List   `tfsdk:"state_values_file"`
	StateValuesSet          types.List   `tfsdk:"state_values_set"`
	StateValuesSetString    types.List   `tfsdk:"state_values_set_string"`
	StripTrailingCr         types.Bool   `tfsdk:"strip_trailing_cr"`
	Suppress                types.List   `tfsdk:"suppress"`
	SuppressDiff            types.Bool   `tfsdk:"suppress_diff"`
	SuppressOutputLineRegex types.List   `tfsdk:"suppress_output_line_regex"`
	SuppressSecrets         types.Bool   `tfsdk:"suppress_secrets"`
	SyncArgs                types.String `tfsdk:"sync_args"`
	SyncReleaseLabels       types.Bool   `tfsdk:"sync_release_labels"`
	TakeOwnership           types.Bool   `tfsdk:"take_ownership"`
	Validate                types.Bool   `tfsdk:"validate"`
	Values                  types.List   `tfsdk:"values"`
	Wait                    types.Bool   `tfsdk:"wait"`
	WaitForJobs             types.Bool   `tfsdk:"wait_for_jobs"`
}
